const { pool } = require('../config/database');
const logger = require('../config/logger');
const createCsvWriter = require('csv-writer').createObjectCsvWriter;
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Create reports directory if it doesn't exist
const reportsDir = path.join(__dirname, '../../reports');
if (!fs.existsSync(reportsDir)) {
  fs.mkdirSync(reportsDir, { recursive: true });
}

/**
 * Generate daily report
 * GET /api/reports/daily
 */
const generateDailyReport = async (req, res) => {
  try {
    const date = req.query.date || new Date().toISOString().split('T')[0];

    const [records] = await pool.execute(
      `SELECT 
        lr.id,
        lr.borrowed_date,
        lr.due_date,
        lr.returned_date,
        lr.fine_amount,
        u.name as user_name,
        u.email as user_email,
        b.title as book_title,
        b.author as book_author,
        b.isbn,
        CASE 
          WHEN lr.returned_date IS NOT NULL THEN 'Returned'
          WHEN DATE(lr.borrowed_date) = ? THEN 'Borrowed'
          ELSE 'Active'
        END as transaction_type
      FROM lending_records lr
      JOIN users u ON lr.user_id = u.id
      JOIN books b ON lr.book_id = b.id
      WHERE DATE(lr.borrowed_date) = ? OR DATE(lr.returned_date) = ?
      ORDER BY lr.borrowed_date DESC, lr.returned_date DESC`,
      [date, date, date]
    );

    logger.info(`Daily report generated by admin ${req.user.id} for date: ${date}`);

    res.json({
      success: true,
      data: {
        date,
        total_transactions: records.length,
        records
      }
    });
  } catch (error) {
    logger.error('Generate daily report error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while generating daily report'
    });
  }
};

/**
 * Generate monthly report
 * GET /api/reports/monthly
 */
const generateMonthlyReport = async (req, res) => {
  try {
    const year = parseInt(req.query.year) || new Date().getFullYear();
    const month = parseInt(req.query.month) || new Date().getMonth() + 1;

    const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
    const endDate = new Date(year, month, 0).toISOString().split('T')[0];

    const [records] = await pool.execute(
      `SELECT 
        lr.id,
        lr.borrowed_date,
        lr.due_date,
        lr.returned_date,
        lr.fine_amount,
        u.name as user_name,
        u.email as user_email,
        b.title as book_title,
        b.author as book_author,
        b.isbn,
        CASE 
          WHEN lr.returned_date IS NOT NULL THEN 'Returned'
          ELSE 'Borrowed'
        END as transaction_type
      FROM lending_records lr
      JOIN users u ON lr.user_id = u.id
      JOIN books b ON lr.book_id = b.id
      WHERE (DATE(lr.borrowed_date) BETWEEN ? AND ?) OR (DATE(lr.returned_date) BETWEEN ? AND ?)
      ORDER BY lr.borrowed_date DESC, lr.returned_date DESC`,
      [startDate, endDate, startDate, endDate]
    );

    // Calculate summary statistics
    const totalBorrows = records.filter(r => r.transaction_type === 'Borrowed').length;
    const totalReturns = records.filter(r => r.transaction_type === 'Returned').length;

    logger.info(`Monthly report generated by admin ${req.user.id} for ${year}-${month}`);

    res.json({
      success: true,
      data: {
        year,
        month,
        start_date: startDate,
        end_date: endDate,
        total_transactions: records.length,
        total_borrows: totalBorrows,
        total_returns: totalReturns,
        records
      }
    });
  } catch (error) {
    logger.error('Generate monthly report error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while generating monthly report'
    });
  }
};

/**
 * Export daily report as CSV
 * GET /api/reports/daily/export/csv
 */
const exportDailyReportCSV = async (req, res) => {
  try {
    const date = req.query.date || new Date().toISOString().split('T')[0];

    const [records] = await pool.execute(
      `SELECT 
        lr.id,
        lr.borrowed_date,
        lr.due_date,
        lr.returned_date,
        lr.fine_amount,
        u.name as user_name,
        u.email as user_email,
        b.title as book_title,
        b.author as book_author,
        b.isbn,
        CASE 
          WHEN lr.returned_date IS NOT NULL THEN 'Returned'
          WHEN DATE(lr.borrowed_date) = ? THEN 'Borrowed'
          ELSE 'Active'
        END as transaction_type
      FROM lending_records lr
      JOIN users u ON lr.user_id = u.id
      JOIN books b ON lr.book_id = b.id
      WHERE DATE(lr.borrowed_date) = ? OR DATE(lr.returned_date) = ?
      ORDER BY lr.borrowed_date DESC, lr.returned_date DESC`,
      [date, date, date]
    );

    const filename = `daily_report_${date}.csv`;
    const filepath = path.join(reportsDir, filename);

    const csvWriter = createCsvWriter({
      path: filepath,
      header: [
        { id: 'id', title: 'Record ID' },
        { id: 'user_name', title: 'User Name' },
        { id: 'user_email', title: 'User Email' },
        { id: 'book_title', title: 'Book Title' },
        { id: 'book_author', title: 'Author' },
        { id: 'isbn', title: 'ISBN' },
        { id: 'borrowed_date', title: 'Borrowed Date' },
        { id: 'due_date', title: 'Due Date' },
        { id: 'returned_date', title: 'Returned Date' },
        { id: 'fine_amount', title: 'Fine Amount' },
        { id: 'transaction_type', title: 'Transaction Type' }
      ]
    });

    await csvWriter.writeRecords(records);

    logger.info(`Daily CSV report exported by admin ${req.user.id} for date: ${date}`);

    res.download(filepath, filename, (err) => {
      if (err) {
        logger.error('Error downloading CSV file:', err);
      }
      // Optionally delete file after download
      // fs.unlinkSync(filepath);
    });
  } catch (error) {
    logger.error('Export daily CSV error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while exporting CSV report'
    });
  }
};

/**
 * Export daily report as PDF
 * GET /api/reports/daily/export/pdf
 */
const exportDailyReportPDF = async (req, res) => {
  try {
    const date = req.query.date || new Date().toISOString().split('T')[0];

    const [records] = await pool.execute(
      `SELECT 
        lr.id,
        lr.borrowed_date,
        lr.due_date,
        lr.returned_date,
        lr.fine_amount,
        u.name as user_name,
        u.email as user_email,
        b.title as book_title,
        b.author as book_author,
        b.isbn,
        CASE 
          WHEN lr.returned_date IS NOT NULL THEN 'Returned'
          WHEN DATE(lr.borrowed_date) = ? THEN 'Borrowed'
          ELSE 'Active'
        END as transaction_type
      FROM lending_records lr
      JOIN users u ON lr.user_id = u.id
      JOIN books b ON lr.book_id = b.id
      WHERE DATE(lr.borrowed_date) = ? OR DATE(lr.returned_date) = ?
      ORDER BY lr.borrowed_date DESC, lr.returned_date DESC`,
      [date, date, date]
    );

    const filename = `daily_report_${date}.pdf`;
    const filepath = path.join(reportsDir, filename);

    const doc = new PDFDocument();
    const writeStream = fs.createWriteStream(filepath);
    doc.pipe(writeStream);

    // Header
    doc.fontSize(20).text('Daily Library Report', { align: 'center' });
    doc.fontSize(12).text(`Date: ${date}`, { align: 'center' });
    doc.moveDown();

    // Summary
    doc.fontSize(14).text(`Total Transactions: ${records.length}`);
    doc.moveDown();

    // Table header
    doc.fontSize(10);
    let y = doc.y;
    doc.text('ID', 50, y);
    doc.text('User', 80, y);
    doc.text('Book', 200, y);
    doc.text('Borrowed', 350, y);
    doc.text('Returned', 450, y);
    doc.text('Type', 550, y);
    y += 20;
    doc.moveTo(50, y).lineTo(600, y).stroke();
    y += 10;

    // Table rows
    records.forEach((record, index) => {
      if (y > 700) {
        doc.addPage();
        y = 50;
      }
      doc.text(String(record.id), 50, y);
      doc.text(record.user_name.substring(0, 15), 80, y);
      doc.text(record.book_title.substring(0, 20), 200, y);
      doc.text(record.borrowed_date ? new Date(record.borrowed_date).toLocaleDateString() : '', 350, y);
      doc.text(record.returned_date ? new Date(record.returned_date).toLocaleDateString() : '', 450, y);
      doc.text(record.transaction_type, 550, y);
      y += 20;
    });

    doc.end();

    // Wait for PDF to be written
    await new Promise((resolve, reject) => {
      writeStream.on('finish', resolve);
      writeStream.on('error', reject);
    });

    logger.info(`Daily PDF report exported by admin ${req.user.id} for date: ${date}`);

    res.download(filepath, filename, (err) => {
      if (err) {
        logger.error('Error downloading PDF file:', err);
      }
    });
  } catch (error) {
    logger.error('Export daily PDF error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while exporting PDF report'
    });
  }
};

/**
 * Export monthly report as CSV
 * GET /api/reports/monthly/export/csv
 */
const exportMonthlyReportCSV = async (req, res) => {
  try {
    const year = parseInt(req.query.year) || new Date().getFullYear();
    const month = parseInt(req.query.month) || new Date().getMonth() + 1;

    const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
    const endDate = new Date(year, month, 0).toISOString().split('T')[0];

    const [records] = await pool.execute(
      `SELECT 
        lr.id,
        lr.borrowed_date,
        lr.due_date,
        lr.returned_date,
        lr.fine_amount,
        u.name as user_name,
        u.email as user_email,
        b.title as book_title,
        b.author as book_author,
        b.isbn,
        CASE 
          WHEN lr.returned_date IS NOT NULL THEN 'Returned'
          ELSE 'Borrowed'
        END as transaction_type
      FROM lending_records lr
      JOIN users u ON lr.user_id = u.id
      JOIN books b ON lr.book_id = b.id
      WHERE (DATE(lr.borrowed_date) BETWEEN ? AND ?) OR (DATE(lr.returned_date) BETWEEN ? AND ?)
      ORDER BY lr.borrowed_date DESC, lr.returned_date DESC`,
      [startDate, endDate, startDate, endDate]
    );

    const filename = `monthly_report_${year}_${month}.csv`;
    const filepath = path.join(reportsDir, filename);

    const csvWriter = createCsvWriter({
      path: filepath,
      header: [
        { id: 'id', title: 'Record ID' },
        { id: 'user_name', title: 'User Name' },
        { id: 'user_email', title: 'User Email' },
        { id: 'book_title', title: 'Book Title' },
        { id: 'book_author', title: 'Author' },
        { id: 'isbn', title: 'ISBN' },
        { id: 'borrowed_date', title: 'Borrowed Date' },
        { id: 'due_date', title: 'Due Date' },
        { id: 'returned_date', title: 'Returned Date' },
        { id: 'fine_amount', title: 'Fine Amount' },
        { id: 'transaction_type', title: 'Transaction Type' }
      ]
    });

    await csvWriter.writeRecords(records);

    logger.info(`Monthly CSV report exported by admin ${req.user.id} for ${year}-${month}`);

    res.download(filepath, filename, (err) => {
      if (err) {
        logger.error('Error downloading CSV file:', err);
      }
    });
  } catch (error) {
    logger.error('Export monthly CSV error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while exporting CSV report'
    });
  }
};

/**
 * Export monthly report as PDF
 * GET /api/reports/monthly/export/pdf
 */
const exportMonthlyReportPDF = async (req, res) => {
  try {
    const year = parseInt(req.query.year) || new Date().getFullYear();
    const month = parseInt(req.query.month) || new Date().getMonth() + 1;

    const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
    const endDate = new Date(year, month, 0).toISOString().split('T')[0];

    const [records] = await pool.execute(
      `SELECT 
        lr.id,
        lr.borrowed_date,
        lr.due_date,
        lr.returned_date,
        lr.fine_amount,
        u.name as user_name,
        u.email as user_email,
        b.title as book_title,
        b.author as book_author,
        b.isbn,
        CASE 
          WHEN lr.returned_date IS NOT NULL THEN 'Returned'
          ELSE 'Borrowed'
        END as transaction_type
      FROM lending_records lr
      JOIN users u ON lr.user_id = u.id
      JOIN books b ON lr.book_id = b.id
      WHERE (DATE(lr.borrowed_date) BETWEEN ? AND ?) OR (DATE(lr.returned_date) BETWEEN ? AND ?)
      ORDER BY lr.borrowed_date DESC, lr.returned_date DESC`,
      [startDate, endDate, startDate, endDate]
    );

    const totalBorrows = records.filter(r => r.transaction_type === 'Borrowed').length;
    const totalReturns = records.filter(r => r.transaction_type === 'Returned').length;

    const filename = `monthly_report_${year}_${month}.pdf`;
    const filepath = path.join(reportsDir, filename);

    const doc = new PDFDocument();
    const writeStream = fs.createWriteStream(filepath);
    doc.pipe(writeStream);

    // Header
    doc.fontSize(20).text('Monthly Library Report', { align: 'center' });
    doc.fontSize(12).text(`${year}-${String(month).padStart(2, '0')}`, { align: 'center' });
    doc.moveDown();

    // Summary
    doc.fontSize(14);
    doc.text(`Total Transactions: ${records.length}`);
    doc.text(`Total Borrows: ${totalBorrows}`);
    doc.text(`Total Returns: ${totalReturns}`);
    doc.moveDown();

    // Table header
    doc.fontSize(10);
    let y = doc.y;
    doc.text('ID', 50, y);
    doc.text('User', 80, y);
    doc.text('Book', 200, y);
    doc.text('Borrowed', 350, y);
    doc.text('Returned', 450, y);
    doc.text('Type', 550, y);
    y += 20;
    doc.moveTo(50, y).lineTo(600, y).stroke();
    y += 10;

    // Table rows
    records.forEach((record) => {
      if (y > 700) {
        doc.addPage();
        y = 50;
      }
      doc.text(String(record.id), 50, y);
      doc.text(record.user_name.substring(0, 15), 80, y);
      doc.text(record.book_title.substring(0, 20), 200, y);
      doc.text(record.borrowed_date ? new Date(record.borrowed_date).toLocaleDateString() : '', 350, y);
      doc.text(record.returned_date ? new Date(record.returned_date).toLocaleDateString() : '', 450, y);
      doc.text(record.transaction_type, 550, y);
      y += 20;
    });

    doc.end();

    // Wait for PDF to be written
    await new Promise((resolve, reject) => {
      writeStream.on('finish', resolve);
      writeStream.on('error', reject);
    });

    logger.info(`Monthly PDF report exported by admin ${req.user.id} for ${year}-${month}`);

    res.download(filepath, filename, (err) => {
      if (err) {
        logger.error('Error downloading PDF file:', err);
      }
    });
  } catch (error) {
    logger.error('Export monthly PDF error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while exporting PDF report'
    });
  }
};

module.exports = {
  generateDailyReport,
  generateMonthlyReport,
  exportDailyReportCSV,
  exportDailyReportPDF,
  exportMonthlyReportCSV,
  exportMonthlyReportPDF
};

